# ====== Usuall default
#seed = 10086
proj_name = "P5_iICL_toy"

# ==== Model related
gpt_type = "tiny"

# ========= Data related
s_ratio = 0.1
train_data = "tasks_train_simple"
eval_data = "tasks_test_simple"

# ========= IL setting
init_strategy = "mile"
generations = 1

# ========= Training
eval_interval = 500
int_rounds = 400000
dis_rounds = 10
dis_loss = "ce_sample"
int_lr = 0.001
imi_lr = 0.0001

#run_name = "mile_smp_dis1000"
run_name = "baseline"