# ====== Usuall default
#seed = 10086
proj_name = "P5_iICL_toy"

# ==== Model related
gpt_type = "tiny"

# ========= Data related
s_ratio = 0.1
train_data = "tasks_train_simple"
eval_data = "tasks_test_simple"

# ========= IL setting
init_strategy = "mile"
generations = 10

# ========= Training
eval_interval = 500
int_rounds = 80000
dis_rounds = 100
dis_loss = "ce_sample"
int_lr = 0.001
imi_lr = 0.00001

run_name = "mile_smp_dis5000_slr_int80k"
#run_name = "baseline"